@startuml
title Conviction in admirable friendship & dhamma conditions heedfulness (MN 95)
start
while (effluent-free?) is (no)
    repeat :seek better admirable friendship;
    repeat while (observes purifed qualities in teacher) is (no)
    repeat
        fork
            :places **conviction (in teacher)**;
            :visits;
            :grows close;
            :lends ear;
            :hears the dhamma;
        fork again
            -> **{has conviction in the admirable friend}**;
            :develops a **sense of shame**;
        end fork {and}
        while (remembering the dhamma?) is (yes) 
            fork
                :remembers the dhamma;
                :penetrates the meaning of those dhammas;
                :comes to an agreement through **pondering** 
                **those dhammas**;
            fork again
            -> **{has conviction in the dhamma}**;
                :develops a **sense of compunction**;
            end fork {and}
            if (fear causation?) is (no) then
              break;
            endif
            fork
                :desire arises;
                :becomes willing;
                :contemplates the dhamma;
                :exerts oneself;
            fork again
                :reflect on failings of oneself & others;
                floating note right: AN 8:7
                :reflect on attainments of oneself & others;
                if (Gladly would I let the flesh & blood in my body dry up...\nthere will be no relaxing my persistence) is (yes) then 
                  :discerns heedfulness;
                  floating note right: AN 2:5
                else (no)
                  :discerns heedlessness;
                endif
                
            end fork
        end while
    repeat while (admirable friend arouses sense of shame?) is (yes)
endwhile
stop
@enduml

@startuml
title Having a sense of shame & having a sense of compunction, one is heedful
hide empty members
left to right direction

class "Admirable Friendship" as AF
class "Sense of Shame" as SOS
class "Sense of Compunction" as SOC

class Mind {
  + **heedfullness** percentage
  + **appropriate attention** percentage

  + greed\passion percentage
  + aversion percentage
  + delusion percentage

  + **has sense of shame & compunction()**
  + **comes to an agreement()**
  + **reflects()**

  + enter and remain in concentration()
  + arouse sensual desire/lust()
  + indulge in sensuality()
  + is inclined towards renunciation()
}

abstract class Being {
  + release()
}

class Practitioner extends Being {
  + **seeks admirable friendship()**
  + exercises generosity()
}

AF --> Dhamma: teaches
Practitioner --> Being
Practitioner -r-> AF: acquires\n{w/ conviction} >
Practitioner -r-> Dhamma: remembers, ..., ponders\n{w/ conviction} >
SOS .u. (AF, Practitioner): {born out disappointing teacher}
SOC .d. (Dhamma, Practitioner): {born out of fearing causation}

class SkillfulMentalQualities {
  + **conviction** percentage
  + persistence percentage
  + mindfulness percentage
  
  + desire percentage
  + willing percentage
  + contemplation percentage
  + **exertion** percentage
  
  + **right view** percentage
  + right resolve percentage
  + right speech percentage
  + right action percentage
  + right livelihood percentage
  ...
}

class UnskillfulMentalQualities {
  + ignorance percentage
}

Being *--> SkillfulMentalQualities
Being *--> UnskillfulMentalQualities


class Action <<kamma>> {}
Being *-l-> "*" Action: heir to their >
Being *--> Mind
Mind::heedfullness ..> SOS: arises from >
Mind::heedfullness ..> SOC: arises from >
Mind::reflects ..> Action: reflects on failings & attainments WRT >

Mind o-r-> Concentration: experiences meditative dwellings via >

class Concentration {
  + tranquility:
    + first jhana
    + second jhana
    + third jhana
    + forth jhana
    + themeless
}

class Training {
  + exerts(relentless_percentage)
  + practice heightened virtue()
  + practice heightened mind()
  + practice heightened discernment()
  
  + seclusion()
  + solitude()
  + self-control()
  + self-restraint()

  + abandon()
  + resume()
}

Practitioner --> Training: follows instructions for >

class "Sensual desire/Lust" as sdl
sdl .. (Practitioner, Being): {entangled with others}
Training::seclusion ..> sdl: lack of seclusion/solitude & restraint leads to >
Mind --> Training: needs to be >
@enduml