@startuml
title Heedfulness results in appropriate attention, right view & exertion (AN 10:76)
start
while (having a **sense of shame or compunction**?) is (yes)
    :becomes **more heedful** (ie. less heedless);
    :develops non-apathy;
    :becomes easy to correct;
    :seek more admirable friendship;
    :develops conviction;
    :develops non-stinginess;
    :arouses persistence;
    :develops non-restlessness;
    :develops restraint;
    :develops virtue;
    :develops desire to see noble ones;
    :develops desire to hear noble dhamma;
    :having a mind not bent on critism;
    :develops mindfulness & alertness;
    :develops unscattered awareness;
    :develops **appropriate attention**;
    :acquires **right view** & the right path;
end while
stop
@enduml
